### ISSUE TITLE
Title: 2048 Game

### ISSUE THREAD

**Issue by saketh-05** [swapnilsparsh/30DaysOfJavaScript#1547] opened 2024-05-27 13:31 UTC
**This is a very exciting, fun and logical game which is purely built using HTML, CSS and JavaScript.**

### Why should this be added?

- Easy to understand and Fun to play
- It tests reasoning and logical abilities of the player
- This project will have modern look and feel
- You have to join consecutive blocks with numbers to add them.
- Then new blocks will appear at random on the board
- Before the board is completely filled with blocks, Add blocks to form 2048 number.

Screenshot:
![2048](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/134281589/45f40ec8-9703-4cc9-8f0a-68f76426570d)

Please assign me this issue under GSSOC 2024.

**Comment by swapnilsparsh** [comment] 2024-05-28 18:32
@saketh-05 All the best 👍🏻

**Comment by AsmitaMishra24** [comment] 2024-05-29 15:38
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by saketh-05** [comment] 2024-05-29 16:45
@AsmitaMishra24 I have created this issue was assigned this task, raise any other issue u want to work and mentors/admin will assign you.

**Comment by AsmitaMishra24** [comment] 2024-05-29 17:32
I know @saketh-05,
However, according to GSSoC rules, If the person to whom the issue is assigned becomes inactive, the task should be reassigned to the next available person. 
So I just wanted to express my willingness to work on the task if this situation arises.

**Comment by katarianikita2003** [comment] 2024-05-30 13:33
Hello @saketh-05  , I want to work on this issue. Can you please assign it to me?

**Comment by swapnilsparsh** [comment] 2024-06-01 20:21
@saketh-05 Any update ?

**Comment by saketh-05** [comment] 2024-06-02 00:54
@swapnilsparsh  Almost finished working on the project, Just need to make few changes to improve look and feel. Sorry for the delay as I had sem exams till day before yestarday.

**Closed** 2024-06-17 18:15 UTC
Labels: gssoc
